### ISSUE TITLE
Experience description is incorrectly positioned

### ISSUE THREAD

**Issue by pimentum** [anthony1x6000/ROBLOX2016stylus#54] opened 2024-06-30 16:57 UTC
## [Released](https://github.com/anthony1x6000/ROBLOX2016stylus/releases) CSS bug report
Experience descriptions are shifted upwards, causing some text to be hidden behind the game thumbnails

**To Reproduce**
1. Go to any experience page, i.e. https://www.roblox.com/games/204990346/Tiny-Tanks

![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/174267644/45a89235-82cc-4303-8bce-1d53d651e663)

**What it should look like**

![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/174267644/3c46d464-a6c8-4373-ab74-0dd675a6dab6)

**Desktop**
 - OS: Win 11
 - Browser: Chrome
 - Script Version 1.3.0
 - Display resolution 1920 x 1080

**Comment by anthony1x6000** [comment] 2024-06-30 17:50
I am unable to reproduce this. If others could test this as well, that would be great. This issue may have been a cause of a reigon specific site update.

**Comment by SammyGoesHowdy** [comment] 2024-07-02 14:19
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/105883916/d79f71dd-9f92-4244-ac85-19fc557d9322)
i have this same issue, keep in mind my account location is set to the united kingdom

**Comment by SammyGoesHowdy** [comment] 2024-07-03 10:46
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/105883916/bd4c9e82-b78f-40aa-8efe-6a3e7402a352)
light mode issue seems to be fixed in new update, but the description is still misaligned

**Comment by SammyGoesHowdy** [comment] 2024-07-03 10:46
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/105883916/f1202194-ce65-4faa-9256-e6bb71f806ea)
same thing happens in light mode

**Comment by anthony1x6000** [comment] 2024-07-03 15:03
Hmmm I thought modifying the padding would do something. I made changes previosuly to give the description a background and to forcefully put the header above that background. Commenting out or removing the [following lines](https://github.com/anthony1x6000/ROBLOX2016stylus/blob/4098ebeed9a85bcf0c3d1a8a352a985d72f68f89/devDownloads/roblox2016-preLatest.user.css#L3892-L3910) should fix the issue.
Unless someone else can aid in fixing this issue, I cannot do much.

**Comment by SammyGoesHowdy** [comment] 2024-07-06 18:45
![image](https://github.com/anthony1x6000/ROBLOX2016stylus/assets/105883916/97ef8301-3580-4577-9b14-f87007765594)
That fixed the issue.

**Comment by annoy205** [comment] 2024-07-13 19:28
If you have btroblox or anything installed it causes this issue

**Comment by anthony1x6000** [comment] 2024-07-15 15:43
> If you have btroblox or anything installed it causes this issue

Yeah, that seems to be the issue. Thank you for that information and sorry for begin inactive for a while, busy with school. 
I'll go ahead and make a fix.

**Closed** 2024-07-15 15:57 UTC
